# Generated by Django 3.0.5 on 2020-04-29 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountryCases',
            fields=[
                ('Country_ID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Country_Name', models.CharField(max_length=100)),
                ('Confirmed', models.IntegerField()),
                ('Deaths', models.IntegerField()),
                ('Recovered', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StateCases',
            fields=[
                ('State_Name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('State_fips', models.IntegerField()),
                ('State_abbr', models.CharField(max_length=3)),
                ('Confirmed', models.IntegerField()),
                ('Confirmed_Per_100000_People', models.CharField(max_length=20)),
                ('Deaths', models.IntegerField()),
                ('Deaths_Per_100000_People', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StateProjection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('State_Name', models.CharField(max_length=100)),
                ('date_reported', models.DateField()),
                ('allbed_mean', models.FloatField()),
                ('ICUbed_mean', models.FloatField()),
                ('InvVen_mean', models.FloatField()),
                ('deaths_mean_daily', models.FloatField()),
                ('totalDeath_mean', models.FloatField()),
                ('bedshortage_mean', models.FloatField()),
                ('icushortage_mean', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CountyCases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('County_fips', models.IntegerField()),
                ('County_name', models.CharField(max_length=100)),
                ('Confirmed', models.IntegerField()),
                ('Confirmed_Per_100000_People', models.CharField(max_length=20)),
                ('Deaths', models.IntegerField()),
                ('Deaths_Per_100000_People', models.CharField(max_length=20)),
                ('State_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finalcore.StateCases')),
            ],
        ),
    ]
